### ISSUE TITLE
Why is run_3dSwap.py taking hours for simple image to image face swap?

### ISSUE THREAD

**Issue by arnold408** [lyx0208/3dSwap#3]
Hi,
I ran run_3dSwap.py
It is taking hours to complete.
All other face libraries takes just a few seconds for image to image face swap.
Please suggest code for simple source image to target image face swap (using pre-trained model)
Thanks

**Comment by lyx0208** [comment]
Hi! I run the run_3dSwap.py script on my 3090 GPU in about 7-8 minutes, just as we mentioned in the paper. Can you provide more information about the device you use?

**Comment by arnold408** [comment]
Hi, thanks for reply.
I have tested many face swapping codes like insightface inswapper or simswap etc for image to image face swap using their pre-trained model.
They take just 4 seconds on my linux server with CPU only.
Your code is taking hours. 
Please suggest if we can do image to image face swap using your pre-trained model.
If yes, please provide code.
Thanks

**Comment by lyx0208** [comment]
According to our paper, the test-time finetuning is part of the pipeline of 3dSwap since it generates multi-view results and geometry rather than a single-view swapped face as the approaches you mentioned. Thus it's not possible (and we mentioned this as our weakness) to perform an image-to-image face swapping in a few seconds with our model.

**Comment by arnold408** [comment]
Thanks for reply.
The result image of 3dSwap is very good compared to other face swap libraries.
Please try to provide quick image to image face swap result like other libraries.
Thanks
